include:
  - project: 'kits-maxiv/cfg-maxiv-gitlabci'
    file: '/Docker.gitlab-ci.yml'

variables:
  DOCKER_REGISTRY: "harbor.maxiv.lu.se/daq"
  IMAGE_NAME: "dranspose/danmax-tomo"
  DOCKER_BUILD_EXTRA_ARGS: --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA
